server:
  port: 8091
spring:
  config:
    activate:
      on-profile: local
  kafka:
    topic:  library-events
    template:
      default-topic: library-events
    consumer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: library-events-listener-group
      auto-offset-reset: latest
    admin:
      bootstrap-servers: localhost:9092
      
      
#With spring.kafka.producer properties -- Kafka Template will be created